In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf # tensorflow from google, it is low level API
import keras

import cv2
from keras.models import load_model
from PIL import Image

In [2]:
def  face_extractor(img):
    faces = face_cascade.detectMultiScale(img, scaleFactor = 1.5 , minNeighbors = 5)
    if faces is ():
        return None
    
    
    for (x ,y , w, h)  in faces:
        cv2.rectangle(img , (x,y) , (x+w , y+h), (0,0, 255) , 2)
        roi =  img[y :y+h , x:x+w]
    
    return roi

<>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Legion\AppData\Local\Temp\ipykernel_17512\3321755764.py:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


In [3]:
face_cascade =  cv2.CascadeClassifier(r"C:\Users\Legion\OneDrive\Pictures\haarcascade_frontalface_default.xml")
model = load_model('mask_nomask_LSTM.h5')  # name of m y model---creted after CNN

video_capture =cv2.VideoCapture(0) # front camera
while True:
    ret,frame = video_capture.read()
    
    face = face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face , (200,200)) # based on the way u have build the cnn model
        im = Image.fromarray(face , 'RGB')
        
        
        img_array = np.array(im)
        
        img_array = np.expand_dims(img_array ,  axis = 0)
        pred = model.predict(img_array)
        print(pred)
        
        
        name = "None Matching"

        if pred[0][0]  > .5:
            name ="Masked"
        elif pred[0][1]  > .5:
            name = 'Mask is not there , Put on the mask' 
        cv2.putText(frame ,name , (75 , 75) , cv2.FONT_HERSHEY_COMPLEX , 1 , (255 , 0, 0) , 2)    
    else:
        cv2.putText(frame ,"Face not found" , (75 , 75 ) , cv2.FONT_HERSHEY_COMPLEX ,1 , (255 , 0, 0) , 2)
    cv2.imshow('Video' , frame)    
        
    if cv2.waitKey(20) & 0xff == ord('q') : 
        break

video_capture.release()
cv2.destroyAllWindows()



1/1 [==============================] - 0s 183ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 28ms/step
[[0. 1.]]
1/1 [==============================] - 0s 28ms/step
[[0. 1.]]
1/1 [==============================] - 0s 26ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 32ms/step
[[0. 1.]]
1/1 [==============================] - 0s 24ms/step
[[0. 1.]]
1/1 [

1/1 [==============================] - 0s 32ms/step
[[0. 1.]]
1/1 [==============================] - 0s 24ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 24ms/step
[[0. 1.]]
1/1 [==============================] - 0s 29ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 29ms/step
[[0. 1.]]
1/1 [==============================] - 0s 28ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 28ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 27ms/step
[[0. 1.]]
1/1 [==============================] - 0s 23ms/step
[[0. 1.]]
1/1 [==============================] - 0s 28ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 23ms/step
[[0. 1.]]
1/1 [==============================] - 0s 32ms/step
[[0. 1.]]
1/1 [==============================] - 0s 32ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 24ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 31ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 23ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 22ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 23ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 15ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[0. 1.]]
1/1 [==============================] - 0s 23ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 24ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 25ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[0. 1.]]
1/1 [==============================] - 0s 24ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[0. 1.]]
1/1 [==============================] - 0s 28ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 23ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 23ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 24ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 29ms/step
[[0. 1.]]
1/1 [==============================] - 0s 26ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 25ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 32ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 23ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 30ms/step
[[0. 1.]]
1/1 [==============================] - 0s 23ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 30ms/step
[[0. 1.]]
1/1 [==============================] - 0s 37ms/step
[[0. 1.]]
1/1 [==============================] - 0s 25ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 26ms/step
[[0. 1.]]
1/1 [==============================] - 0s 25ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[0. 1.]]
1/1 [==============================] - 0s 24ms/step
[[0. 1.]]
1/1 [==============================] - 0s 24ms/step
[[0. 1.]]
1/1 [==============================] - 0s 23ms/step
[[0. 1.]]
1/1 [==============================] - 0s 24ms/step
[[0. 1.]]
1/1 [==============================] - 0s 15ms/step
[[0. 1.]]
1/1 [==============================] - 0s 28ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 27ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[0. 1.]]
1/1 [==============================] - 0s 29ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 23ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 25ms/step
[[0. 1.]]
1/1 [==============================] - 0s 26ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 15ms/step
[[0. 1.]]
1/1 [==============================] - 0s 31ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 23ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[0. 1.]]
1/1 [==============================] - 0s 25ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 30ms/step
[[0. 1.]]
1/1 [==============================] - 0s 31ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 15ms/step
[[0. 1.]]
1/1 [==============================] - 0s 32ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 34ms/step
[[0. 1.]]
1/1 [==============================] - 0s 32ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 32ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[0. 1.]]
1/1 [==============================] - 0s 24ms/step
[[0. 1.]]
1/1 [==============================] - 0s 31ms/step
[[0. 1.]]
1/1 [==============================] - 0s 30ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 24ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[0. 1.]]
1/1 [==============================] - 0s 23ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 23ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 26ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[0. 1.]]
1/1 [==============================] - 0s 31ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 15ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 32ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 27ms/step
[[0. 1.]]
1/1 [==============================] - 0s 31ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 27ms/step
[[0. 1.]]
1/1 [==============================] - 0s 28ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 32ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 23ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 32ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 34ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 27ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 23ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 15ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 16ms/step
[[0. 1.]]
1/1 [==============================] - 0s 30ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 20ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 19ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 21ms/step
[[0. 1.]]
1/1 [==============================] - 0s 23ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [===

1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 32ms/step
[[0. 1.]]
1/1 [==============================] - 0s 18ms/step
[[0. 1.]]
1/1 [==============================] - 0s 17ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[0. 1.]]


error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:971: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'
